### PR TITLE
Add lint and build checks for pull requests onto main

### PR DESCRIPTION
**Pull request by gxrsti**
This pr adds a github action to check lint and build for a pr onto the main branch.

@mezotv you can set a branch protection rule which needs these checks to succeed before merging.

### CODE REVIEW

**Comment by mezotv** [comment]
Would it be possible to give the workflow a more descriptive name and perhaps add @Podskio and @mezotv as a reviewer using the same workflow?

**Comment by gxrsti** [comment]
Sure, what name would you like? 

The reviewer workflow is possible but needs to be in a seperate workflow file since this one is running on every commit to the pr and the reviewer workflow should only run once when the pr is opened.

**Comment by mezotv** [comment]
Something as simple as "Pull Request Check" would do the job or even "Lint and Build" for the reviewer workflow a separate file would be fine yea.

**Comment by gxrsti** [comment]
Sure. I have to correct myself for the reviewer workflow. This will be done with the .github/CODEOWNERS file.

**Comment by gxrsti** [comment]
Should be fine like this

**Review by mezotv — APPROVED** [review]
Looks good thanks for this!

**Pull request merged**
