### PR TITLE
✨ Tiny Website Tweaks!

### PR DESCRIPTION
**Pull request by ArnavK-09**
> **#Hacktoberfest**

# Description

Little website tweaks for better ux, as follows
- Text content tweak
- ~~Navbar links animation~~
- Better font visibility normal -> semibold
- Good Length SEO Title
- Apple touch icon, favicon
- Commands section heading changed
- Features Keywords highlight
- Paragraphs rephrasing done 
- New hero Button, with animation
- Invite Button Highlighted in UX
- New Vanilla css animation ` shakme `
- Formated some files
- Aria-label in links

> Related To #45 #43 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] The code works fine on my machine.
- [x] I have modified the build steps if changed.

### CODE REVIEW

**Comment by mezotv** [comment]
Seems like you need to replace some of those quotes with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;` so nextjs can compile.

**Comment by ArnavK-09** [comment]
@mezotv 👋 #hacktoberfest squashit

**Review by mezotv — CHANGES_REQUESTED** [review]
I checked it out a bit but to be honest I don't really like the changes you have done to the navbar. Could you revert those?

**Comment by ArnavK-09** [comment]
> I checked it out a bit but to be honest I don't really like the changes you have done to the navbar. Could you revert those?
@mezotv 

Sorry, but yes I changed navbar to original!

**Comment by ArnavK-09** [comment]
@mezotv push?

**Comment by mezotv** [comment]
> @mezotv push?

I just synced it with the maik branch!

**Comment by ArnavK-09** [comment]
> > @mezotv push?
> 
> I just synced it with the main branch!

Ok, j was just asking when you will merge this pull request to main


Thanks

**Comment by mezotv** [comment]
> Ok, j was just asking when you will merge this pull request to main

Will merge this once the team agrees and 2 saff members accepted the pr. Due note that we are insanely busy at the moment.

**Comment by gxrsti** [comment]
Thank you for your input and for taking the time to create this pull request.
However, we want to let you know that we've decided not to merge these changes. We appreciate your efforts, but we don't see these changes as useful at the moment.

If you have any other ideas or contributions you'd like to make, please let us know and we'd be happy to consider them. Thanks again for your efforts!

**Pull request closed without merging**
