### PR TITLE
feat(question-packs): [WOU-99] Add icons and finish integration

### PR DESCRIPTION
**Pull request by Jester0027**
https://linear.app/would-you/issue/WOU-99/questions-page-integration

### CODE REVIEW

**Review by dpaulos6 — APPROVED** [review]

**Review by mezotv — CHANGES_REQUESTED** [review]
Could you change the color of the "Use Pack" button to #FFFFFF? Also I think it would make more sense to finish the full feature before merging into main.

**Comment by Jester0027** [comment]
> Also I think it would make more sense to finish the full feature before merging into main.

Is the main branch the deployed version or will there be release branches ?
What branch policy should we go for otherwise ?
btw this current branch was checked out and partially merged on main (not by me) in another pr, I just added some stuff I didn't finish.

**Comment by Jester0027** [comment]
I'm going to create a dev branch for now

**Comment by mezotv** [comment]
> Is the main branch the deployed version or will there be release branches ? What branch policy should we go for otherwise ? btw this current branch was checked out and partially merged on main (not by me) in another pr, I just added some stuff I didn't finish.

The main branch is the one that would get deployed yea, we could make a release branch tho technically.

**Comment by Jester0027** [comment]
> Could you change the color of the "Use Pack" button to #FFFFFF?

Done, I adjusted some other colors too

**Pull request merged**
