### PR TITLE
refactor: fix hydration errors, reduce button size

### PR DESCRIPTION
**Pull request by gxrsti**
This pr addresses hydration errors occurring on '/privacy' and reduces the button size to look better (in my opinion).

Before:

image

After:

image

### CODE REVIEW

**Comment by mezotv** [comment]
Ill have to disagree on the button sizes. Could you revert that?

**Comment by gxrsti** [comment]
> Ill have to disagree on the button sizes. Could you revert that?

Sure

**Review by Podskio — APPROVED** [review]
Thanks for the help!

**Review by mezotv — APPROVED** [review]
Thanks!

**Pull request merged**
