### PR TITLE
Refine styling and responsiveness in the blog view

### PR DESCRIPTION
**Pull request by luckyklyist**
Issue No:   #38 
Improved styling and responsiveness for blog post components in the mobile view.

https://github.com/Would-You-Bot/website/assets/35479077/2c2f162b-93a3-4694-8391-f7aad7ef48f8

### CODE REVIEW

**Comment by luckyklyist** [comment]
> Will check this once I get home! Feel free to look at the other issues @luckyklyist !
Sure .

**Review by mezotv — CHANGES_REQUESTED** [review]
On medium-sized phones the image on the right looks really squished together, fixing that would be awesome!
image

On even smaller phones this looks really out of place:
image
Perhaps make the box grow larger down to the bottom so the image has more space as well as the tags and user logo!

**Comment by Podskio** [comment]
Fixes #38

**Comment by mezotv** [comment]
Hey @luckyklyist any update on this?

**Comment by mezotv** [comment]
Hey @luckyklyist I noticed you gave a thumbs up but haven't actually replied yet. Anything wrong?

**Comment by luckyklyist** [comment]
will be  working on it today @mezotv

**Comment by luckyklyist** [comment]
https://github.com/Would-You-Bot/website/assets/35479077/e010802a-882d-4bc1-9545-cd701cd48f98

**Comment by gxrsti** [comment]
Hey @luckyklyist,

I've improved the code to meet our expectations for merging this pull request.
Thank you for contributing. If you have any more suggestions or would like to work on something else, please let us know.

**Pull request merged**
