### PR TITLE
reading progress bar on blog pages

### PR DESCRIPTION
**Pull request by AksBad007**
Hi @mezotv  , this is in reference to #30 .

### CODE REVIEW

**Comment by mezotv** [comment]
Would you be able to provide a screenshot of how this is looking on your end?

**Comment by AksBad007** [comment]
Sure.

Screenshot 2023-10-02 at 2 07 37 AM

**Review by mezotv — CHANGES_REQUESTED** [review]
I feel like the current bar is a bit to big maybe decrease the size of it?

**Comment by AksBad007** [comment]
Hi @mezotv , is it fine now?

Screenshot 2023-10-02 at 2 21 28 AM

**Comment by mezotv** [comment]
> Hi @mezotv , is it fine now?
> 
> Screenshot 2023-10-02 at 2 21 28 AM
> 

Thats much better thank you I will see what @Podskio has to say!

**Review by Podskio — APPROVED** [review]
Looks great! Thank you for the contribution!

**Pull request merged**
