### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by ayushmankoley**
fixed https://github.com/Would-You-Bot/website/issues/24

### CODE REVIEW

**Review by Podskio — CHANGES_REQUESTED** [review]
I don't think it makes sense to add commands on the website repo.

**Review by mezotv — CHANGES_REQUESTED** [review]
Hey thanks for your pull request but would it be possible to remove the license from the readme?

**Comment by ayushmankoley** [comment]
sure guys making changes

**Comment by ayushmankoley** [comment]
@mezotv @Podskio check now and lmk if any changes

**Review by mezotv — APPROVED** [review]
Looks good. Thanks for your request!

**Comment by mezotv** [comment]
Feel free to explore the other issues in case you are interested in contributing even more!

**Comment by ayushmankoley** [comment]
@mezotv sure and updated a spelling mistake rereview if necessary

**Comment by mezotv** [comment]
> @mezotv sure and updated a spelling mistake rereview if necessary

Yea looks good!

**Review by Podskio — APPROVED** [review]

**Pull request merged**
