### PR TITLE
refactor: stored all the links in map and code is more readable now

### PR DESCRIPTION
**Pull request by Ayushpanditmoto**

### CODE REVIEW

**Comment by mezotv** [comment]
Im currently on vacation so I might not have time to review this today. Pod should be able to take a look tho!

**Comment by Ayushpanditmoto** [comment]
@mezotv its just a small changes brother

**Comment by mezotv** [comment]
> @mezotv its just a small changes brother

I will take a look tomorrow once I get the time. Thank you!

**Review by Podskio — APPROVED** [review]

**Comment by Ayushpanditmoto** [comment]
@mezotv @Podskio  label please give hactoberfest-accepted here otherwise it will not counted

**Pull request merged**
