### PR TITLE
Docs: Upgrade README.md

### LINKED ISSUE #58: Upgrade readme
Upgrade the readme to add a screenshot of the site, how to run the project and add more information into the readme to make it look better. This should be fairly advanced for it to not count as a spam pr.

Be creative with it too!

### PR DESCRIPTION
**Pull request by jfmartinz**
# Description

Fixes #58 

In this PR, I've worked on enhancing the overall presentation of our documentation. Here's a breakdown of the changes I've made:

1. **Visual Enhancements:**
   - I've added the Would You bot server logo to give contributors and users a clear visual representation of our bot.
   - Introduced badges to provide quick insights into the project.

2. **Improved Clarity:**
   - To enhance readability, I've renamed some table of contents sections and headings. For instance, "Introduction" and "About Bot" have been refined for better understanding.

3. **Features Section:**
   - I've included a new "Features" section to help users understand the benefits of our bot, assisting them in deciding whether it's suitable for their Discord server. Visual aids such as images have also been added to make this section more engaging.

4. **Codeblocks:**
   - Implemented codeblocks where necessary to improve code presentation and readability.

5. **Contributing Guidelines Reference:**
   - To facilitate our contributors, I've included a reference to the contributing.md file, making it easier for them to find the guidelines on how to contribute effectively.

6. **Engaging Invitation:**
   - I've revamped the invitation message to pique the interest of potential users, aiming to attract more users than the previous message.

If you have any feedback, suggestions, or further changes in mind, please don't hesitate to share them. Thank you for considering these enhancements!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

ss:
image
image
image
image

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] The code works fine on my machine.
- [x] I have modified the build steps if changed.

### CODE REVIEW

**Comment by mezotv** [comment]
Looks good so far I will review it once im home!

**Review by mezotv — CHANGES_REQUESTED** [review]
Could you use this as the big image on top?

Front Page

**Comment by jfmartinz** [comment]
> Could you use this as the big image on top?
> 
> Front Page

Thanks. How about the h1? Should I put it on the top or leave it in the bottom?

**Comment by jfmartinz** [comment]
image

**Comment by jfmartinz** [comment]
image

**Comment by jfmartinz** [comment]
image

**Comment by mezotv** [comment]
> Thanks. How about the h1? Should I put it on the top or leave it in the bottom?

I would put that on the top.

**Comment by jfmartinz** [comment]
> > Thanks. How about the h1? Should I put it on the top or leave it in the bottom?
> 
> I would put that on the top.

Okay thank you. Anything else? All goods?

**Comment by mezotv** [comment]
> > > Thanks. How about the h1? Should I put it on the top or leave it in the bottom?
> > 
> > I would put that on the top.
> 
> Okay thank you. Anything else? All goods?

Thats all from my side, thanks!

**Review by mezotv — APPROVED** [review]
Looks good to me make sure you change the heading and image tho!

**Comment by jfmartinz** [comment]
> Looks good to me make sure you change the heading and image th

Thanks. I made the changes already. Please check :)

**Comment by mezotv** [comment]
> > Looks good to me make sure you change the heading and image th
> 
> Thanks. I made the changes already. Please check :)

Awesome, I already approved the merge request will need to wait for pod to do so too!

**Comment by mezotv** [comment]
I have had a little chat with the team and we have agreed not to merge your request. While we are super grateful for it, it does not seem like a good fit for this type of project. I apologise.

**Comment by jfmartinz** [comment]
> I have had a little chat with the team and we have agreed not to merge your request. While we are super grateful for it, it does not seem like a good fit for this type of project. I apologise.

Okay. Thanks

**Pull request closed without merging**
