### PR TITLE
Solved Responsiveness Problem in small devices

### LINKED ISSUE #76: [Bug]: UI Breaks in small mobile
### Contact Details

mustafaazad533@gmail.com

### What happened?

When I go to the small mobile device the component cut by the screen.

image

I want to work on this issue.

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mustafaazad03**
# Description

Responsiveness Issue solved by changing designs.

Fixes #76 .

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshort
image
image

# Checklist:

- [x] I have performed a self-review of my code
- [x] The code works fine on my machine.
- [x] I have modified the build steps if changed.

### CODE REVIEW

**Comment by gxrsti** [comment]
Hey @mustafaazad03!
First of all, thanks for your contribution! I have a few things that I would like to get done for this pr to be merged:

- Please remove the package-lock.json file from this pr, make sure to use `pnpm` instead of `npm` when running the project.
- The Discord embeds all have different widths on small devices, please fix this so that they all have the same margins.

image

If you need any help with these changes, feel free to reach out to me!

**Review by mezotv — CHANGES_REQUESTED** [review]
See @gxrsti comment ^^

**Comment by mustafaazad03** [comment]
Hi @gxrsti, Thank you for your response, I will remove package-lock.json file but the changes of this is because when I try to make that like the below card the inner text and divs overlaps and that didn't look good at all, but yah I will try to find some solution out of this

**Review by mustafaazad03 — COMMENTED** [review]
Removed Package-lock.json

**Comment by mustafaazad03** [comment]
Hi @gxrsti @mezotv ,
image

Issue solved as suggested.

**Review by gxrsti — CHANGES_REQUESTED** [review]
Hey @mustafaazad03!
Sorry for the delay. I'm quite busy atm. It seems like there are still some margin issues with the Discord embeds. Could you please look into it again?

image

**Comment by mezotv** [comment]
Are you still working on this @mustafaazad03?

**Comment by mustafaazad03** [comment]
Yes, I make changes as per suggestions

**Comment by mustafaazad03** [comment]
Yes, I am working on it.

**Comment by mustafaazad03** [comment]
image

I made the alignment consistent as suggested. Please review changes and let me know if there's any changes.

**Review by gxrsti — APPROVED** [review]
Hey @mustafaazad03!
I've gone ahead and made some small text wrapping adjustments to align with our preferences. 
Thanks for your contribution, this pr can be merged now!

**Pull request merged**
