### PR TITLE
feat:added release worflow file for actions

### LINKED ISSUE #57: Add automatic release
Add a workflow to automatically publish a new release and increment the number similar to this one https://github.com/EddieHubCommunity/BioDrop/blob/main/.github/workflows/release.yml

### PR DESCRIPTION
**Pull request by Siddharth9890**
# Description

Please include a summary of the changes and the related issue.

Fixes #57 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# Checklist:

- [X] I have performed a self-review of my code
- [X] I have modified the build steps if changed.
@mezotv i have added the file tested it as well there are no errors and job runs as well this i tested on a different node js repo not this one but the action file is same
image

### CODE REVIEW

**Comment by mezotv** [comment]
Hey thanks for your contribution, can you describe the workflow and how it's working?

**Comment by Siddharth9890** [comment]
Sure here are the steps

1. So after pushing to main this all happens
2. Firstly a temp branch is created and we are switched to it 
3. Then we update the version in package.json file so for example 1.0.0-> 1.0.1 if a patch and it is also stored in output 
4. Changelog is created using this TriPSs/conventional-changelog-action@v3
5. The action then creates a PR and merges it to main

**Comment by mezotv** [comment]
> Sorry for the previous one this time i have changed the file to simpler one here is the output it gives but the condition being the commit messages should follow conventional method like feat,fix,chore and so on then it detects the increment version automatically and does it maybe we can use husky to fix pre commit message hook  @mezotv 
> image
> 

Does the workflow also increment zhe number in the package.json file? Also how would husty work?

**Comment by Siddharth9890** [comment]
Yes the version inside package json does gets updated depending upon commit message but for husky that would be a separate PR altogether because it requires changing the commands in package.json.

**Comment by mezotv** [comment]
> Yes the version inside package json does gets updated depending upon commit message but for husky that would be a separate PR altogether because it requires changing the commands in package.json.

If you wanna work on that you are free to open another issue!

**Comment by mezotv** [comment]
Hey @Siddharth9890 , I just had a talk with the team and we all think this would make more sense on [another repo](https://github.com/Would-You-Bot/client) would you be able to add this and the husky changes to there and close this one? I'm really sorry for all the stress btw!

**Comment by Siddharth9890** [comment]
Sure you guys can create the issue assign it to me and i do it @mezotv

**Pull request closed without merging**
