### PR TITLE
Fixes #60 Added Copy To Clipboard When Clicked On The Command

### LINKED ISSUE #60: [REQUEST] - Copy command on click
### Description

On the https://wouldyoubot.gg/commands page allow the user to click the usage command and copy it to their clipboard. 

You could change the text of the command to --Click to copy-- when hovering over it and drag down the opacity of the text a bit. And then copy once clicked you copy the command to the users clipboard!

### Basic Example

_No response_

### PR DESCRIPTION
**Pull request by Honey2339**
# Description

Added a feature to copy the command

Fixes #60

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] The code works fine on my machine.
- [x] I have modified the build steps if changed.

### CODE REVIEW

**Comment by mezotv** [comment]
Could you attach a video of how it looks like on your machine?

**Comment by Honey2339** [comment]
This is how it looks on my machine

https://github.com/Would-You-Bot/website/assets/121949298/b8ca2371-5e0c-42b2-866e-4db9143d7713

**Review by mezotv — CHANGES_REQUESTED** [review]
Looks really good however could you make a little transition so it looks a bit smother?

**Comment by Honey2339** [comment]
Yeah sure working on it.

**Comment by Honey2339** [comment]
Oh you mean that it should not copy "/debug *<cmd>*"? right?

**Comment by mezotv** [comment]
> Oh you mean that it should not copy /debug "cmd"? right?

Thats fine but it should only copy /debug and not the <subcommand> part of it.

**Comment by Honey2339** [comment]
I have implemented the copying of only command part but im finding it hard to implement a transition between the text.

**Comment by mezotv** [comment]
> I have implemented the copying of only command part but im finding it hard to implement a transition between the text.

Thats fine! Ill check in a bit.

**Comment by Podskio** [comment]
> I have implemented the copying of only command part but im finding it hard to implement a transition between the text.

Try splitting the whitespace, eg `"/debug <subcommand>".split(" ")[0]`

**Review by Podskio — APPROVED** [review]

**Review by mezotv — APPROVED** [review]

**Pull request merged**
